name: HoodPlugin
version: 0.1
main: HoodPlugin
commands:
  fasttravelpointset:
    description: Sets a fast travel point
    aliases:
      - ftps
    usage: /fasttravelpointset <Name> <X> <Y> <Z> <Radius>

  fasttravelpointdelete:
    description: Deletes a fast travel point
    aliases:
      - ftpd
    usage: /fasttravelpointdelete <name>

  fasttravel:
    description: Go to a fast travel point
    aliases:
      - ft
    usage: /fasttravel <name>

  fasttravellist:
    description: Lists all fast travel points and their coordinates
    aliases:
      - fts
    usage: /fasttravellist