name: HoodPlugin
version: 0.1
main: HoodPlugin
api-version: 1.20

commands:
  fasttravelpointset:
    description: Sets a fast travel point
    aliases:
      - ftps
    usage: /fasttravelpointset <Name> <X> <Y> <Z> <Radius>
  fasttravelpointdelete:
    description: Deletes a fast travel point
    aliases:
      - ftpd
    usage: /fasttravelpointdelete name
  fasttravel:
    description: Go to a fast travel <name>
    aliases:
      - ft
    usage: /fasttravel <name>
  fasttravellist:
    description: Lists all fast travel points and their coordinates
    aliases:
      - ftl
    usage: /fasttravellist
  fasttravelban:
    description: Bans a player from fast travelling
    usage: /fasttravelban <name>
  fasttravelunban:
    description: Unbans a player from fast travelling
    usage: /fasttravelunban <name>

  jailset:
    description: Sets a jail
    usage: /jailset <Name> <X> <Y> <Z>
  jail:
    description: Sends the targeted player to jail.
    usage: /jail <Name>
  jailfree:
    description: Sets a player free from jail.
    usage: /jailfree <Name>
  jaildelete:
    description: Deletes a jail.
    usage: /jaildelete <Name>
  jaillist:
    description: Lists all jails and their coordinates
    usage: /jaillist

  bal:
    description: Check balance
    usage: /<command>
  pay:
    description: Pay someone an amount
    usage: /<command> <player-name>/[org <org-name>] <amount>
  balop:
    description: Operator command for editing balances
    usage: /balop <set/add/sub> <player> <amount>

  permissions:
    myplugin.admin:
      description: Allows access to admin commands in MyPlugin
      default: op

  org:
    description: Organisation based commands
    usage: /org help
    aliases:
      - o
      - organisation