name: HoodPlugin
version: 0.1
main: HoodPlugin
api-version: 1.20.1
commands:
  fasttravelpointset:
    description: Sets a fast travel point
    aliases:
      - ftps
    usage: /fasttravelpointset <Name> <X> <Y> <Z> <Radius>
  fasttravelpointdelete:
    description: Deletes a fast travel point
    aliases:
      - ftpd
    usage: /fasttravelpointdelete name
  fasttravel:
    description: Go to a fast travel point
    aliases:
      - ft
    usage: /fasttravel name
  bal:
    description: Check balance
    usage: /<command>
  pay:
    description: Pay someone an amount
    usage: /<command> <player> <amount>
  balop:
    description: Operator command for editing balances
    usage: /balop <set/add/sub> <player> <amount>